
CREATE TABLE public.equipment_catalog (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category_value text NOT NULL,
  category_label text NOT NULL,
  equipment_name text NOT NULL,
  brand text,
  type text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.equipment_catalog ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read equipment_catalog" ON public.equipment_catalog FOR SELECT TO public USING (true);
CREATE POLICY "Anyone can insert equipment_catalog" ON public.equipment_catalog FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Anyone can update equipment_catalog" ON public.equipment_catalog FOR UPDATE TO public USING (true);
CREATE POLICY "Anyone can delete equipment_catalog" ON public.equipment_catalog FOR DELETE TO public USING (true);

-- Seed from existing catalog data
INSERT INTO equipment_catalog (category_value, category_label, equipment_name, brand, type) VALUES
-- Bensin-/motorverktøy - Motorsag
('bensinverktoy','Bensin-/motorverktøy','Motorsag','Stihl','O 23 C'),
('bensinverktoy','Bensin-/motorverktøy','Motorsag','Stihl','MS 261'),
('bensinverktoy','Bensin-/motorverktøy','Motorsag','Stihl','MS 362'),
('bensinverktoy','Bensin-/motorverktøy','Motorsag','Husqvarna','45'),
('bensinverktoy','Bensin-/motorverktøy','Motorsag','Husqvarna','450'),
('bensinverktoy','Bensin-/motorverktøy','Motorsag','Husqvarna','550 XP'),
('bensinverktoy','Bensin-/motorverktøy','Motorsag','Husqvarna','572 XP'),
('bensinverktoy','Bensin-/motorverktøy','Motorsag','Jonsered','CS 2152 W'),
('bensinverktoy','Bensin-/motorverktøy','Motorsag','Jonsered','CS 2255'),
-- Ryddesag
('bensinverktoy','Bensin-/motorverktøy','Ryddesag','Stihl','FS 131/R'),
('bensinverktoy','Bensin-/motorverktøy','Ryddesag','Stihl','FS 560 C'),
('bensinverktoy','Bensin-/motorverktøy','Ryddesag','Stihl','FS 450K'),
('bensinverktoy','Bensin-/motorverktøy','Ryddesag','Stihl','FS 460 C'),
('bensinverktoy','Bensin-/motorverktøy','Ryddesag','Honda','435E'),
('bensinverktoy','Bensin-/motorverktøy','Ryddesag','Honda','UMK 435'),
('bensinverktoy','Bensin-/motorverktøy','Ryddesag','Husqvarna','165RX E'),
('bensinverktoy','Bensin-/motorverktøy','Ryddesag','Husqvarna','535RX'),
-- Kantklipper
('bensinverktoy','Bensin-/motorverktøy','Kantklipper','Stihl','FSA 56'),
('bensinverktoy','Bensin-/motorverktøy','Kantklipper','Stihl','FSA 90'),
('bensinverktoy','Bensin-/motorverktøy','Kantklipper','Honda','UMC425E'),
-- Plenklipper
('bensinverktoy','Bensin-/motorverktøy','Plenklipper','Ariens','200 M 42 CE'),
('bensinverktoy','Bensin-/motorverktøy','Plenklipper','John Deere','LTR 180'),
('bensinverktoy','Bensin-/motorverktøy','Plenklipper','Husqvarna','R 13 C'),
-- El.verktøy
('el_verktoy','El.verktøy','Vinkelsliper','Bosch','GWS 18V-125C'),
('el_verktoy','El.verktøy','Vinkelsliper','Bosch','GWS 1-125C'),
('el_verktoy','El.verktøy','Vinkelsliper','Bosch','GWS9-125C'),
('el_verktoy','El.verktøy','Vinkelsliper','Bosch','GWS 24-230'),
('el_verktoy','El.verktøy','Vinkelsliper','Bosch','GWS 11-125'),
('el_verktoy','El.verktøy','Vinkelsliper','Hitachi','G 23SF2'),
('el_verktoy','El.verktøy','Vinkelsliper','Hitachi','G13SW'),
('el_verktoy','El.verktøy','Vinkelsliper','Hitachi','G 23 UBY'),
('el_verktoy','El.verktøy','Vinkelsliper','Hitachi','G23MRU'),
('el_verktoy','El.verktøy','Vinkelsliper','Hitachi','G18 DSL'),
('el_verktoy','El.verktøy','Vinkelsliper','Hitachi','G13 SE2'),
('el_verktoy','El.verktøy','Vinkelsliper','Hitachi','G13 SB3'),
('el_verktoy','El.verktøy','Vinkelsliper','Hitachi','G18 DBBVL'),
('el_verktoy','El.verktøy','Vinkelsliper','Milwaukee','AWS 18-125'),
('el_verktoy','El.verktøy','Vinkelsliper','Metabo','PAG-GF35'),
('el_verktoy','El.verktøy','Vinkelsliper','Wurth','AWS 18-125'),
('el_verktoy','El.verktøy','Muttertrekker','Milwaukee','M18 FIW2F12'),
('el_verktoy','El.verktøy','Muttertrekker','Milwaukee','M180NEFH1WF23'),
('el_verktoy','El.verktøy','Muttertrekker','Milwaukee','M18ONEFI'),
('el_verktoy','El.verktøy','Muttertrekker','Milwaukee','M180NEHIWF34'),
('el_verktoy','El.verktøy','Muttertrekker','Bosch','GDS 18V-EC250'),
('el_verktoy','El.verktøy','Muttertrekker','Bosch','GDX 18V-200'),
('el_verktoy','El.verktøy','Muttertrekker','Bosch','GDS 18V-LI HT'),
('el_verktoy','El.verktøy','Muttertrekker','Hitachi','WR 18 DL'),
('el_verktoy','El.verktøy','Muttertrekker','Hitachi','WR 18 DBDC'),
('el_verktoy','El.verktøy','Muttertrekker','Hitachi','WR 14 DM'),
('el_verktoy','El.verktøy','Muttertrekker','Hitachi','WR 18 BN'),
('el_verktoy','El.verktøy','Muttertrekker','Hitachi','WR 18 BDL'),
('el_verktoy','El.verktøy','Muttertrekker','Makita','6905 H SA'),
('el_verktoy','El.verktøy','Skrumaskin','Milwaukee','M18 ONEDD2'),
('el_verktoy','El.verktøy','Drill','Bosch','GSR 18V-EC'),
('el_verktoy','El.verktøy','Drill','Bosch','GSB 18V 85C'),
('el_verktoy','El.verktøy','Drill','Hitachi','DS 14 DSL'),
('el_verktoy','El.verktøy','Drill','Hitachi','DS18 DSL'),
('el_verktoy','El.verktøy','Drill','Hitachi','DV 18 DSDL'),
('el_verktoy','El.verktøy','Drill','Hitachi','DS 18 DL2'),
('el_verktoy','El.verktøy','Drill','Wurth','ABS 18SD 18'),
('el_verktoy','El.verktøy','Slagbormaskin','Bosch','UBH 2/20 RLE'),
('el_verktoy','El.verktøy','Slagbormaskin','Bosch','UH 2/20 SE'),
('el_verktoy','El.verktøy','Slagbormaskin','Bosch','PSB 650 RE'),
('el_verktoy','El.verktøy','Slagbormaskin','Bosch','GBH 8-45 DV'),
('el_verktoy','El.verktøy','Slagbormaskin','Bosch','SDS+ UBH2-20SE'),
('el_verktoy','El.verktøy','Slagbormaskin','Bosch','GBHS-40-DCE450'),
('el_verktoy','El.verktøy','Slagbormaskin','Hitachi','DH26 PB'),
('el_verktoy','El.verktøy','Slagbormaskin','Hitachi','DH24 PC3'),
('el_verktoy','El.verktøy','Slagbormaskin','Hitachi','DH 18 DSL'),
('el_verktoy','El.verktøy','Slagbormaskin','Hitachi','DH 36 DAL'),
('el_verktoy','El.verktøy','Slagbormaskin','Hitachi','DH2 PC3'),
('el_verktoy','El.verktøy','Slagbormaskin','Hitachi','DH24 PB'),
('el_verktoy','El.verktøy','Slagbormaskin','Hitachi','DH 40 MRY'),
('el_verktoy','El.verktøy','Slagbormaskin','Hitachi','DP28PMY'),
('el_verktoy','El.verktøy','Slagbormaskin','Wurth','ABH 18'),
('el_verktoy','El.verktøy','Slagbormaskin','Metabo','750113'),
('el_verktoy','El.verktøy','Bajonettsag','Milwaukee','M18FHZ'),
('el_verktoy','El.verktøy','Bajonettsag','Bosch','GSA 900'),
('el_verktoy','El.verktøy','Bajonettsag','Bosch','GSA 18V 180 SL'),
('el_verktoy','El.verktøy','Bajonettsag','Bosch','GSA18V-32'),
('el_verktoy','El.verktøy','Bajonettsag','Hitachi','CR 18 DSL'),
('el_verktoy','El.verktøy','Bajonettsag','Hitachi','CR'),
('el_verktoy','El.verktøy','Stikksag','Bosch','GST 60 PEE'),
('el_verktoy','El.verktøy','Stikksag','Bosch','PST 680'),
('el_verktoy','El.verktøy','Stikksag','Bosch','650 PE'),
('el_verktoy','El.verktøy','Stikksag','Bosch','0601 580033 E'),
('el_verktoy','El.verktøy','Stikksag','Hitachi','CJ 18DSL'),
('el_verktoy','El.verktøy','Stikksag','Hitachi','CJ110MVA E'),
('el_verktoy','El.verktøy','Stikksag','Black & Decker','KS 999'),
('el_verktoy','El.verktøy','Sirkelsag','Bosch','GKS 18V-57 G'),
('el_verktoy','El.verktøy','Sirkelsag','Hitachi','C 18DSL'),
('el_verktoy','El.verktøy','Sirkelsag','Black & Decker','DN 56'),
('el_verktoy','El.verktøy','Sirkelsag','Black & Decker','KS855'),
('el_verktoy','El.verktøy','Kabelkutter','Milwaukee','M18 HCC45'),
('el_verktoy','El.verktøy','Kabelkutter','Cembre','B-TC 055'),
('el_verktoy','El.verktøy','Kabelkutter','Cembre','B-TC O4'),
('el_verktoy','El.verktøy','Multiverktøy','Bosch','PMF multi 180'),
('el_verktoy','El.verktøy','Multiverktøy','Bosch','PMF 250 CES'),
('el_verktoy','El.verktøy','Multiverktøy','Bosch','GOP18V-28 E'),
('el_verktoy','El.verktøy','Multiverktøy','Hikoki','CV 18DBL'),
('el_verktoy','El.verktøy','Varmluftpistol','Steinel','HL 500'),
('el_verktoy','El.verktøy','Varmluftpistol','Bosch','PHG 500-2'),
('el_verktoy','El.verktøy','Varmluftpistol','Black & Decker','CD701'),
('el_verktoy','El.verktøy','Varmluftpistol','Black & Decker','HG991'),
('el_verktoy','El.verktøy','Varmluftpistol','Wurth','HLG 2000'),
('el_verktoy','El.verktøy','Hovel','Bosch','PHO 3100'),
('el_verktoy','El.verktøy','Slipemaskin','Bosch','PDS7AE'),
('el_verktoy','El.verktøy','Slipemaskin','Bosch','PSS2'),
('el_verktoy','El.verktøy','Slipemaskin','Bosch','PSS 240AE'),
('el_verktoy','El.verktøy','Slipemaskin','Skil','77310'),
('el_verktoy','El.verktøy','Slipemaskin','Perles','SRE 5-8135'),
('el_verktoy','El.verktøy','Pressverktøy','Cembre','B135LN-C'),
('el_verktoy','El.verktøy','Pressverktøy','Cembre','D1350 L-C'),
('el_verktoy','El.verktøy','Pressverktøy','Cembre','D131L-C'),
('el_verktoy','El.verktøy','Pressverktøy','Cembre','B1300 L-C'),
('el_verktoy','El.verktøy','Pressverktøy','Elpress','PVL1300'),
('el_verktoy','El.verktøy','Pressverktøy','ALFRA','03200'),
('el_verktoy','El.verktøy','Magnetboremaskin','Rotabroach','Commando 40'),
('el_verktoy','El.verktøy','Magnetboremaskin','Rotabroach','CM/405/3'),
('el_verktoy','El.verktøy','Båndsag','Bosch','GCB 18V-LI'),
('el_verktoy','El.verktøy','Kapp og gjærsag','Dewalt','DW 712 QS'),
('el_verktoy','El.verktøy','Kapp og gjærsag','Dewalt','S DE7025-YJ'),
('el_verktoy','El.verktøy','Elektrisk fil','GP','2'),
-- Kjøretøy
('kjøretøy','Kjøretøy','Snøskuter','Lynx','Ranger 600 E-TEC'),
('kjøretøy','Kjøretøy','Snøskuter','Lynx','59 Yeti 550'),
('kjøretøy','Kjøretøy','Snøskuter','Skidoo','Summit 85'),
('kjøretøy','Kjøretøy','Snøskuter','Skidoo','Tundra 600 HO E-TEC'),
('kjøretøy','Kjøretøy','Snøskuter','Polaris','850 SKS'),
-- Maskin
('maskin','Maskin','Personløfter','DINO','180 XT'),
('maskin','Maskin','Personløfter','Palazzani','TZX 190'),
('maskin','Maskin','Personløfter','Nifty','120 T'),
('maskin','Maskin','Personløfter','Nifty','150'),
('maskin','Maskin','Personløfter','JLG','660 SJ'),
-- Utstyr
('utstyr','Utstyr','Sveiseapparat','Esab','180'),
('utstyr','Utstyr','Sveiseapparat','Lincoln','V 130S'),
('utstyr','Utstyr','Sveiseapparat','Lincoln','Handymig 80A'),
('utstyr','Utstyr','Sveiseapparat','Castolin','Powermax 304300'),
('utstyr','Utstyr','Sveiseapparat','Castolin','Powermax 1504'),
('utstyr','Utstyr','Sveiseapparat','Aorweld','MIG 202'),
('utstyr','Utstyr','Sveiseapparat','Race','1403'),
('utstyr','Utstyr','Skjerebrenner',NULL,NULL),
('utstyr','Utstyr','Løftebukk','Omer','Vega 120'),
('utstyr','Utstyr','Løftebukk','Tee Lift','T6 S,ST'),
('utstyr','Utstyr','Benksliper',NULL,NULL);
